---
title: "Forecast script"
output: github_document
---

```{r imports, message = FALSE}
library(tidyverse)
library(data.table)
library(lubridate)
```

```{r read_files, include = FALSE}
###                                                                                 ###
# IT IS NOT YET KNOWN WHAT THE FINAL PATH WILL BE AND IF THE FILES COME TO US CLEANED #
###                                                                                 ###  

# Get all the files
PATH <- "/home/esa/production_forecasts/data/FACS/"
files <- list.files(path = PATH, pattern = "FAC0091_*")  # Character vector of file names

# Compile a dataframe by going over all files
dlist <- list()
for (i in files) {
  # Read a single file to a df called d
  d <- read.delim(file = paste0(PATH, "/", i), header = FALSE, sep = ";", stringsAsFactors = FALSE, colClasses = 'character')
  
  if(length(d) == 26){
    d <- d[, !(names(d) %in% c("V10"))]  # The column numbers unfortunately vary between files, so we'll adjust
    }
  
  colnames(d) <- c("V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "V10",
                   "V11", "V12", "V13", "V14", "V15", "V16", "V17", "V18", "V19", "V20",
                   "V21", "V22", "V23", "V24", "V25")  # This is done so as to have easier column handling later on
  dlist[[i]] <- d
}

d <- as.data.frame(rbindlist(dlist, fill = TRUE))
```

```{r modify_dataframe, include = FALSE}
# Divide into distributions (P) and returns (R)
P <- d[d$V1 == "P", ]
R <- d[d$V1 == "R", ]

# For distributions, we'll keep Distribution date, Quantity, ABO type, Volume, Exp date
keep <- c("V12", "V14", "V18", "V20", "V22", "V24")
distr <- P[keep]
colnames(distr) <- c("date", "product", "quantity", "ABO", "volume", "exp")

# For returns we keep the return date and quantity
keep <- c("V4", "V7")
retrn <- R[keep]
colnames(retrn) <- c("date", "quantity")

# Datify
distr$date <- dmy(distr$date); distr$exp <- dmy(distr$exp)
retrn$date <- dmy(retrn$date)

# Numerify
distr$quantity <- as.numeric(distr$quantity); distr$volume <- as.numeric(distr$volume)
retrn$quantity <- as.numeric(retrn$quantity)

# Product codes for red cell products
red.codes <- c("budTR001", "A0071V00", "A0074V00", "A0092VA0", "A0092VB0", 
               "E3844V00", "E3845V00", "E3846VA0", "E3846VB0", "E3846VC0",
               "E3846V00", "E3847VA0", "E3847VB0", "E3847VC0", "E3847V00",
               "E3936VA0", "E3936VB0", "E3939V00", "E3940V00", "E4683V00",
               "E7668V00", "E7673V00", "E4999V00", "E5000V00")

red.distr <- distr[distr$product %in% red.codes, ]

# Product codes for platelets
plat.codes <- c("budTR002", "trEnnApu", "A0004V00", "A0005V00", "A0006V00", "A0007V00", "A0008V00",
                "A0086VA0", "A0086VB0", "A0086V00", "A0088V00", "A0088VA0", "A0088VB0", "A0089V00",
                "A0089VB0", "A0089VA0", "A0090V00", "A0090VA0", "A0090VB0", "A0018V00", "A0020V00", 
                "A0021V00", "A0021VA0", "A0021VB0", "A0047V00", "A0049V00", "A0051V00", "A0054V00",
                "A0055V00", "A0056V00", "A0057V00", "A0059V00", "A0060V00", "A0067VA0", "A0067VB0",
                "A0067V00", "A0068VA0", "A0068VB0", "A0068V00", "A0075V00", "A0101V00", "A0102V00",
                "E3949V00", "E3953V00", "E3954V00", "E3955V00", "E3956V00", "E3957V00", "E3958V00",
                "E3959V00", "E3960V00", "E3961V00", "E3962V00", "E3963V00", "E3964V00", "E3965V00", 
                "E3966V00", "E3968VA0", "E3968VB0", "E3968V00", "E3970V00", "E3971V00", "E3973V00",
                "E3974V00", "E3976V00", "E3981V00", "E3995V00", "E3996V00", "E3997V00", "E3997VA0",
                "E3997VB0", "E4002V00", "E4004V00", "E6782V00", "E6783V00", "E6953V00", "E6860V00",
                "E6874VA0", "E6874V00", "E6874VB0", "E6875VB0", "E6875V00", "E7530V00", "E7530VA0",
                "E7530VB0", "E7531V00", "E7531VA0", "E7531VB0", "E6875VA0")

plat.distr <- distr[distr$product %in% plat.codes, ]
```


```{r create_datasets, include = FALSE}
# Create a full sequence of dates for imputation purposes
all.dates <- (seq.Date(min(all.red$date),
                       max(all.red$date),
                       "day"))
###           ###
#   RED CELLS   #
###           ###
all.red <- aggregate(red.distr$quantity, by = list(red.distr$date), sum); colnames(all.red) <- c("date", "pcs")
# Merge into a whole set with NAs
all.red <- merge(x = data.frame(date = all.dates),
                 y = all.red,
                 all.x = TRUE)
# Replace with zeroes
all.red[is.na(all.red)] <- 0
# Cut to time after 2014
all.red <- all.red[all.red$date >= as.Date("2014-01-01"), ]


# O minus
Ominus <- red.distr[red.distr$ABO == "O -", ]
Ominus.distr <- aggregate(Ominus$quantity, by = list(Ominus$date), sum); colnames(Ominus.distr) <- c("date", "pcs")
# Merge into a whole set with NAs
Ominus.distr <- merge(x = data.frame(date = all.dates),
                      y = Ominus.distr,
                      all.x = TRUE)
# Replace with zeroes
Ominus.distr[is.na(Ominus.distr)] <- 0
# Cut to time after 2014
Ominus.distr <- Ominus.distr[Ominus.distr$date >= as.Date("2014-01-01"), ]

# O plus
Oplus <- red.distr[red.distr$ABO == "O +", ]
Oplus.distr <- aggregate(Oplus$quantity, by = list(Oplus$date), sum); colnames(Oplus.distr) <- c("date", "pcs")
# Merge into a whole set with NAs
Oplus.distr <- merge(x = data.frame(date = all.dates),
                     y = Oplus.distr,
                     all.x = TRUE)
# Replace with zeroes
Oplus.distr[is.na(Oplus.distr)] <- 0
# Cut to time after 2014
Oplus.distr <- Oplus.distr[Oplus.distr$date >= as.Date("2014-01-01"), ]

# A minus
Aminus <- red.distr[red.distr$ABO == "A -", ]
Aminus.distr <- aggregate(Aminus$quantity, by = list(Aminus$date), sum); colnames(Aminus.distr) <- c("date", "pcs")
# Merge into a whole set with NAs
Aminus.distr <- merge(x = data.frame(date = all.dates),
                      y = Aminus.distr,
                      all.x = TRUE)
# Replace with zeroes
Aminus.distr[is.na(Aminus.distr)] <- 0
# Cut to time after 2014
Aminus.distr <- Aminus.distr[Aminus.distr$date >= as.Date("2014-01-01"), ]

# A plus
Aplus <- red.distr[red.distr$ABO == "A +", ]
Aplus.distr <- aggregate(Aplus$quantity, by = list(Aplus$date), sum); colnames(Aplus.distr) <- c("date", "pcs")
# Merge into a whole set with NAs
Aplus.distr <- merge(x = data.frame(date = all.dates),
                     y = Aplus.distr,
                     all.x = TRUE)
# Replace with zeroes
Aplus.distr[is.na(Aplus.distr)] <- 0
# Cut to time after 2014
Aplus.distr <- Aplus.distr[Aplus.distr$date >= as.Date("2014-01-01"), ]

# B minus
Bminus <- red.distr[red.distr$ABO == "B -", ]
Bminus.distr <- aggregate(Bminus$quantity, by = list(Bminus$date), sum); colnames(Bminus.distr) <- c("date", "pcs")
# Merge into a whole set with NAs
Bminus.distr <- merge(x = data.frame(date = all.dates),
                      y = Bminus.distr,
                      all.x = TRUE)
# Replace with zeroes
Bminus.distr[is.na(Bminus.distr)] <- 0
# Cut to time after 2014
Bminus.distr <- Bminus.distr[Bminus.distr$date >= as.Date("2014-01-01"), ]

# B plus
Bplus <- red.distr[red.distr$ABO == "B +", ]
Bplus.distr <- aggregate(Bplus$quantity, by = list(Bplus$date), sum); colnames(Bplus.distr) <- c("date", "pcs")
# Merge into a whole set with NAs
Bplus.distr <- merge(x = data.frame(date = all.dates),
                     y = Bplus.distr,
                     all.x = TRUE)
# Replace with zeroes
Bplus.distr[is.na(Bplus.distr)] <- 0
# Cut to time after 2014
Bplus.distr <- Bplus.distr[Bplus.distr$date >= as.Date("2014-01-01"), ]

# AB minus
ABminus <- red.distr[red.distr$ABO == "AB-", ]
ABminus.distr <- aggregate(ABminus$quantity, by = list(ABminus$date), sum); colnames(ABminus.distr) <- c("date", "pcs")
# Merge into a whole set with NAs
ABminus.distr <- merge(x = data.frame(date = all.dates),
                       y = ABminus.distr,
                       all.x = TRUE)
# Replace with zeroes
ABminus.distr[is.na(ABminus.distr)] <- 0
# Cut to time after 2014
ABminus.distr <- ABminus.distr[ABminus.distr$date >= as.Date("2014-01-01"), ]

# AB plus
ABplus <- red.distr[red.distr$ABO == "AB+", ]
ABplus.distr <- aggregate(ABplus$quantity, by = list(ABplus$date), sum); colnames(ABplus.distr) <- c("date", "pcs")
# Merge into a whole set with NAs
ABplus.distr <- merge(x = data.frame(date = all.dates),
                      y = ABplus.distr,
                      all.x = TRUE)
# Replace with zeroes
ABplus.distr[is.na(ABplus.distr)] <- 0
# Cut to time after 2014
ABplus.distr <- ABplus.distr[ABplus.distr$date >= as.Date("2014-01-01"), ]


###           ###
#   PLATELETS   #
###           ###
all.plat <- aggregate(plat.distr$quantity, by = list(plat.distr$date), sum); colnames(all.plat) <- c("date", "pcs")
# Merge into a whole set with NAs
all.plat <- merge(x = data.frame(date = all.dates),
                  y = all.plat,
                  all.x = TRUE)
# Replace with zeroes
all.plat[is.na(all.plat)] <- 0
# Cut to time after 2014
all.plat <- all.plat[all.plat$date >= as.Date("2014-01-01"), ]
```

```{r datasets_monthly, include = FALSE}
red.monthly <- aggregate(pcs ~ month(date) + year(date), data = all.red, FUN = sum)
Ominus.monthly <- aggregate(pcs ~ month(date) + year(date), data = Ominus.distr, FUN = sum)
Oplus.monthly <- aggregate(pcs ~ month(date) + year(date), data = Oplus.distr, FUN = sum)
Aminus.monthly <- aggregate(pcs ~ month(date) + year(date), data = Aminus.distr, FUN = sum)
Aplus.monthly <- aggregate(pcs ~ month(date) + year(date), data = Aplus.distr, FUN = sum)
Bminus.monthly <- aggregate(pcs ~ month(date) + year(date), data = Bminus.distr, FUN = sum)
Bplus.monthly <- aggregate(pcs ~ month(date) + year(date), data = Bplus.distr, FUN = sum)
ABminus.monthly <- aggregate(pcs ~ month(date) + year(date), data = ABminus.distr, FUN = sum)
ABplus.monthly <- aggregate(pcs ~ month(date) + year(date), data = ABplus.distr, FUN = sum)
plat.monthly <- aggregate(pcs ~ month(date) + year(date), data = all.plat, FUN = sum)

monthly <- data.frame(date = seq(from = as.Date("2014-01-01"), to = max(distr$date), by = "month"),
                      red = red.monthly$pcs,
                      Ominus = Ominus.monthly$pcs,
                      Oplus = Oplus.monthly$pcs,
                      Aminus = Aminus.monthly$pcs,
                      Aplus = Aplus.monthly$pcs,
                      Bminus = Bminus.monthly$pcs,
                      Bplus = Bplus.monthly$pcs,
                      ABminus = ABminus.monthly$pcs,
                      ABplus = ABplus.monthly$pcs,
                      plat = plat.monthly$pcs)
```

```{r datasets_weekly, include = FALSE}

# ALL.RED
pcslist <- list(); weeklist <- list(); datelist <- list()
j <- 0; k <- 0
for(i in seq(to = length(all.red$date), by = 7)){
  if(j == 52){j <- 0}
  j <- j + 1
  k <- k + 1
  pcslist[[k]] <- sum(all.red$pcs[i : (i + 6)])
  weeklist[[k]] <- j
  datelist[[k]] <- all.red$date[i]
}
red.weekly <- data.frame(week = unlist(weeklist), startdate = as.Date.numeric(unlist(datelist), origin = "1970-01-01"), pcs = unlist(pcslist))

# OMINUS
pcslist <- list(); weeklist <- list(); datelist <- list()
j <- 0; k <- 0
for(i in seq(to = length(Ominus.distr$date), by = 7)){
  if(j == 52){j <- 0}
  j <- j + 1
  k <- k + 1
  pcslist[[k]] <- sum(Ominus.distr$pcs[i : (i + 6)])
  weeklist[[k]] <- j
  datelist[[k]] <- Ominus.distr$date[i]
}
Ominus.weekly <- data.frame(week = unlist(weeklist), startdate = as.Date.numeric(unlist(datelist), origin = "1970-01-01"), pcs = unlist(pcslist))

# OPLUS
pcslist <- list(); weeklist <- list(); datelist <- list()
j <- 0; k <- 0
for(i in seq(to = length(Oplus.distr$date), by = 7)){
  if(j == 52){j <- 0}
  j <- j + 1
  k <- k + 1
  pcslist[[k]] <- sum(Oplus.distr$pcs[i : (i + 6)])
  weeklist[[k]] <- j
  datelist[[k]] <- Oplus.distr$date[i]
}
Oplus.weekly <- data.frame(week = unlist(weeklist), startdate = as.Date.numeric(unlist(datelist), origin = "1970-01-01"), pcs = unlist(pcslist))

# AMINUS
pcslist <- list(); weeklist <- list(); datelist <- list()
j <- 0; k <- 0
for(i in seq(to = length(Aminus.distr$date), by = 7)){
  if(j == 52){j <- 0}
  j <- j + 1
  k <- k + 1
  pcslist[[k]] <- sum(Aminus.distr$pcs[i : (i + 6)])
  weeklist[[k]] <- j
  datelist[[k]] <- Aminus.distr$date[i]
}
Aminus.weekly <- data.frame(week = unlist(weeklist), startdate = as.Date.numeric(unlist(datelist), origin = "1970-01-01"), pcs = unlist(pcslist))

# APLUS
pcslist <- list(); weeklist <- list(); datelist <- list()
j <- 0; k <- 0
for(i in seq(to = length(Aplus.distr$date), by = 7)){
  if(j == 52){j <- 0}
  j <- j + 1
  k <- k + 1
  pcslist[[k]] <- sum(Aplus.distr$pcs[i : (i + 6)])
  weeklist[[k]] <- j
  datelist[[k]] <- Aplus.distr$date[i]
}
Aplus.weekly <- data.frame(week = unlist(weeklist), startdate = as.Date.numeric(unlist(datelist), origin = "1970-01-01"), pcs = unlist(pcslist))

# BMINUS
pcslist <- list(); weeklist <- list(); datelist <- list()
j <- 0; k <- 0
for(i in seq(to = length(Bminus.distr$date), by = 7)){
  if(j == 52){j <- 0}
  j <- j + 1
  k <- k + 1
  pcslist[[k]] <- sum(Bminus.distr$pcs[i : (i + 6)])
  weeklist[[k]] <- j
  datelist[[k]] <- Bminus.distr$date[i]
}
Bminus.weekly <- data.frame(week = unlist(weeklist), startdate = as.Date.numeric(unlist(datelist), origin = "1970-01-01"), pcs = unlist(pcslist))

# BPLUS
pcslist <- list(); weeklist <- list(); datelist <- list()
j <- 0; k <- 0
for(i in seq(to = length(Bplus.distr$date), by = 7)){
  if(j == 52){j <- 0}
  j <- j + 1
  k <- k + 1
  pcslist[[k]] <- sum(Bplus.distr$pcs[i : (i + 6)])
  weeklist[[k]] <- j
  datelist[[k]] <- Bplus.distr$date[i]
}
Bplus.weekly <- data.frame(week = unlist(weeklist), startdate = as.Date.numeric(unlist(datelist), origin = "1970-01-01"), pcs = unlist(pcslist))

# ABMINUS
pcslist <- list(); weeklist <- list(); datelist <- list()
j <- 0; k <- 0
for(i in seq(to = length(ABminus.distr$date), by = 7)){
  if(j == 52){j <- 0}
  j <- j + 1
  k <- k + 1
  pcslist[[k]] <- sum(ABminus.distr$pcs[i : (i + 6)])
  weeklist[[k]] <- j
  datelist[[k]] <- ABminus.distr$date[i]
}
ABminus.weekly <- data.frame(week = unlist(weeklist), startdate = as.Date.numeric(unlist(datelist), origin = "1970-01-01"), pcs = unlist(pcslist))

# ABPLUS
pcslist <- list(); weeklist <- list(); datelist <- list()
j <- 0; k <- 0
for(i in seq(to = length(ABplus.distr$date), by = 7)){
  if(j == 52){j <- 0}
  j <- j + 1
  k <- k + 1
  pcslist[[k]] <- sum(ABplus.distr$pcs[i : (i + 6)])
  weeklist[[k]] <- j
  datelist[[k]] <- ABplus.distr$date[i]
}
ABplus.weekly <- data.frame(week = unlist(weeklist), startdate = as.Date.numeric(unlist(datelist), origin = "1970-01-01"), pcs = unlist(pcslist))

# ALL.PLAT
pcslist <- list(); weeklist <- list(); datelist <- list()
j <- 0; k <- 0
for(i in seq(to = length(all.plat$date), by = 7)){
  if(j == 52){j <- 0}
  j <- j + 1
  k <- k + 1
  pcslist[[k]] <- sum(all.plat$pcs[i : (i + 6)])
  weeklist[[k]] <- j
  datelist[[k]] <- all.plat$date[i]
}
plat.weekly <- data.frame(week = unlist(weeklist), startdate = as.Date.numeric(unlist(datelist), origin = "1970-01-01"), pcs = unlist(pcslist))

weekly <- data.frame(week = red.weekly$week,
                     startdate = red.weekly$startdate,
                     red = red.weekly$pcs,
                     Ominus = Ominus.weekly$pcs,
                     Oplus = Oplus.weekly$pcs,
                     Aminus = Aminus.weekly$pcs,
                     Aplus = Aplus.weekly$pcs,
                     Bminus = Bminus.weekly$pcs,
                     Bplus = Bplus.weekly$pcs,
                     ABminus = ABminus.weekly$pcs,
                     ABplus = ABplus.weekly$pcs,
                     plat = plat.weekly$pcs)
```

## Monthly demand of the past year {.tabset .tabset-fade .tabset-pills}

### All red
```{r}
year.segment <- monthly[(length(monthly$red)-12):(length(monthly$red)-1), ]
obj = TRUE
ggplot(data = head(monthly, -1), aes(x = date, y = red)) + 
  geom_line() +
  geom_smooth(data = year.segment, aes(x = date, y = red), method = "lm", inherit.aes = FALSE) +
  labs(title = "red",
       subtitle = "for a year",
       caption = paste0("Past year's trend has been ", ifelse(test = lm(year.segment$red ~ seq_along(year.segment$red))$coefficients[2] >= 0, 
                                                              yes = "upward.", no = "downward.")),
       x = "Date",
       y = "Blood bags")
```


### By blood type
content

### Platelets
content

### Plasma
```{r}

```

