---
title: "Weekly series tests"
author: "Esa Turkulainen"
date: "2/1/2021"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# echo "rmarkdown::render('forecast_script_FIN.Rmd', clean=TRUE,output_format='html_document',output_file='results/forecast_script_FIN_20201006.Rmd')" | R --slave

# Set working directory
ROOTDIR <- "~/production_forecasts/src/" # Your directory
DATADIR <- "~/production_forecasts/data/FACS"
HISTORYDIR <- "~/production_forecasts/histories/" # monthly
MONTHLYDIR <- paste0(HISTORYDIR, "monthly_") # monthly
WEEKLYDIR <- paste0(HISTORYDIR, "weekly_") # weekly

knitr::opts_chunk$set(root.dir = ROOTDIR, warning = FALSE, message = FALSE) # No warnings for final output
knitr::opts_knit$set(root.dir = ROOTDIR, warning = FALSE, message = FALSE)

# Colorblind palette
# black, orange, sky blue, green,
# yellow, blue, vermilion, purple
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", 
                "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# These colors work server side for now:
palette <- list(1, 1, 1, 0.7, "royalblue2", "deepskyblue1", "darkred", "darkgreen")
names(palette) <- c("alpha80", "alpha95", "alphaSeg", "alphaPred", "fill80", "fill95", "colPred", "colData")
```

```{r imports, message=FALSE, warning=FALSE, echo=FALSE}
library(forecast)
library(ggplot2)
library(gridExtra)
library(knitr)
library(plyr)
library(lubridate)
library(numbers)
library(data.table)
library(R.utils)
library(DT)
library(stringr)
library(hash)
library(htmltools)
library(feasts)
library(tsibble)
library(dplyr)
library(zoo)
source("pffunctions.R")
# Set rolling window size in years
rw_years <- 3
start_date <- as.Date("2014-01-01")
```

```{r read_files, include = FALSE}
# Get all the files
files <- list.files(path = DATADIR, pattern = "FAC0091_*")  # Character vector of file names

# Compile a dataframe by going over all files
dlist <- list()
for (i in files) {
  # Read a single file to a df called d
  d <- read.delim(file = paste0(DATADIR, "/", i), header = FALSE, sep = ";", stringsAsFactors = FALSE, colClasses = 'character')
  
  if(length(d) == 26){
    d <- d[, !(names(d) %in% c("V10"))]  # The column numbers unfortunately vary between files, so we'll adjust
    }
  
  colnames(d) <- c("V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "V10",
                   "V11", "V12", "V13", "V14", "V15", "V16", "V17", "V18", "V19", "V20",
                   "V21", "V22", "V23", "V24", "V25")  # This is done so as to have easier column handling later on
  dlist[[i]] <- d
}

d <- as.data.frame(rbindlist(dlist, fill = TRUE))
```

```{r modify_dataframe, include = FALSE}
# Divide into distributions (P) and returns (R)
P <- d[d$V1 == "P", ]
R <- d[d$V1 == "R", ]

# For distributions, we'll keep Distribution date, Quantity, ABO type, Volume, Exp date
keep <- c("V12", "V14", "V18", "V20", "V22", "V24")
distr <- P[keep]
colnames(distr) <- c("date", "product", "quantity", "ABO", "volume", "exp")

# For returns we keep the return date and quantity
keep <- c("V4", "V5", "V7")
retrn <- R[keep]
colnames(retrn) <- c("date", "product", "quantity")

# Datify
distr$date <- dmy(distr$date); distr$exp <- dmy(distr$exp)
retrn$date <- dmy(retrn$date)

# Numerify
distr$quantity <- as.numeric(distr$quantity); distr$volume <- as.numeric(distr$volume)
retrn$quantity <- as.numeric(retrn$quantity)

# Product codes for red cell products
red.codes <- c("budTR001", "A0071V00", "A0074V00", "A0092VA0", "A0092VB0", 
               "E3844V00", "E3845V00", "E3846VA0", "E3846VB0", "E3846VC0",
               "E3846V00", "E3847VA0", "E3847VB0", "E3847VC0", "E3847V00",
               "E3936VA0", "E3936VB0", "E3939V00", "E3940V00", "E4683V00",
               "E7668V00", "E7673V00", "E4999V00", "E5000V00")

red.distr <- distr[distr$product %in% red.codes, ]
red.retrn <- retrn[retrn$product %in% red.codes, ]

# Product codes for platelets
plat.codes <- c("budTR002", "trEnnApu", "A0004V00", "A0005V00", "A0006V00", "A0007V00", "A0008V00",
                "A0086VA0", "A0086VB0", "A0086V00", "A0088V00", "A0088VA0", "A0088VB0", "A0089V00",
                "A0089VB0", "A0089VA0", "A0090V00", "A0090VA0", "A0090VB0", "A0018V00", "A0020V00", 
                "A0021V00", "A0021VA0", "A0021VB0", "A0047V00", "A0049V00", "A0051V00", "A0054V00",
                "A0055V00", "A0056V00", "A0057V00", "A0059V00", "A0060V00", "A0067VA0", "A0067VB0",
                "A0067V00", "A0068VA0", "A0068VB0", "A0068V00", "A0075V00", "A0101V00", "A0102V00",
                "E3949V00", "E3953V00", "E3954V00", "E3955V00", "E3956V00", "E3957V00", "E3958V00",
                "E3959V00", "E3960V00", "E3961V00", "E3962V00", "E3963V00", "E3964V00", "E3965V00", 
                "E3966V00", "E3968VA0", "E3968VB0", "E3968V00", "E3970V00", "E3971V00", "E3973V00",
                "E3974V00", "E3976V00", "E3981V00", "E3995V00", "E3996V00", "E3997V00", "E3997VA0",
                "E3997VB0", "E4002V00", "E4004V00", "E6782V00", "E6783V00", "E6953V00", "E6860V00",
                "E6874VA0", "E6874V00", "E6874VB0", "E6875VB0", "E6875V00", "E7530V00", "E7530VA0",
                "E7530VB0", "E7531V00", "E7531VA0", "E7531VB0", "E6875VA0")

plat.distr <- distr[distr$product %in% plat.codes, ]
plat.retrn <- retrn[retrn$product %in% plat.codes, ]
```

#Get monthly values summarised by Laura
```{r}
monthly2004 <- read.delim("~/production_forecasts/data/kuukausimyynti.txt")
monthly2004$year <- as.factor(substr(monthly2004$kuukausi, 1, 4))
m2004 <- as.factor(substr(monthly2004$kuukausi, 6, 9))
levels(m2004) <- c(8, 7, 2, 4, 12, 6, 10, 3, 11, 9, 1, 5)
monthly2004$month <- as.character(m2004)
```

```{r create_datasets, include = FALSE}
# Create a full sequence of dates for imputation purposes
all.dates <- (seq.Date(min(red.distr$date),
                       max(red.distr$date),
                       "day"))
###           ###
#   RED CELLS   #
###           ###
all.red <- aggregate(red.distr$quantity, by = list(red.distr$date), sum); colnames(all.red) <- c("date", "pcs")
# Merge into a whole set with NAs
all.red <- merge(x = data.frame(date = all.dates),
                 y = all.red,
                 all.x = TRUE)
# Replace with zeroes
all.red[is.na(all.red)] <- 0
# Cut to time after 2014
all.red <- all.red[all.red$date >= start_date, ]

###           ###
#  RED RETURNS  #
###           ###

all.red.retrn <- aggregate(red.retrn$quantity, by = list(red.retrn$date), sum); colnames(all.red.retrn) <- c("date", "pcs")
# Merge into a whole set with NAs
all.red.retrn <- merge(x = data.frame(date = all.dates),
                 y = all.red.retrn,
                 all.x = TRUE)
# Replace with zeroes
all.red.retrn[is.na(all.red.retrn)] <- 0
# Cut to time after 2014
all.red.retrn <- all.red.retrn[all.red.retrn$date >= start_date, ]


# Extracting types
Ominus.distr <- extract_type(red.distr, "O -",start_date)  # This our custom function, see pffunctions.R
Oplus.distr <- extract_type(red.distr, "O +",start_date)
Aminus.distr <- extract_type(red.distr, "A -",start_date)
Aplus.distr <- extract_type(red.distr, "A +",start_date)
Bminus.distr <- extract_type(red.distr, "B -",start_date)
Bplus.distr <- extract_type(red.distr, "B +",start_date)
ABminus.distr <- extract_type(red.distr, "AB-",start_date)
ABplus.distr <- extract_type(red.distr, "AB+",start_date)


###           ###
#   PLATELETS   #
###           ###
all.plat <- aggregate(plat.distr$quantity, by = list(plat.distr$date), sum); colnames(all.plat) <- c("date", "pcs")
# Merge into a whole set with NAs
all.plat <- merge(x = data.frame(date = all.dates),
                  y = all.plat,
                  all.x = TRUE)
# Replace with zeroes
all.plat[is.na(all.plat)] <- 0
# Cut to time after 2014
all.plat <- all.plat[all.plat$date >= start_date, ]

###           ###
# PLAT RETURNS  #
###           ###
all.plat.retrn <- aggregate(plat.retrn$quantity, by = list(plat.retrn$date), sum); colnames(all.plat.retrn) <- c("date", "pcs")
# Merge into a whole set with NAs
all.plat.retrn <- merge(x = data.frame(date = all.dates),
                  y = all.plat.retrn,
                  all.x = TRUE)
# Replace with zeroes
all.plat.retrn[is.na(all.plat.retrn)] <- 0
# Cut to time after 2014
all.plat.retrn <- all.plat.retrn[all.plat.retrn$date >= start_date, ]
```

```{r weekly}
# remember that this won't work if there are missing days
# cut to first monday
#conct.distr <- tail(all.distr, -5)

pcslist <- list()
weeklist <- list()
datelist <- list()
j <- 0
k <- 0
for(i in seq(to = length(all.red$date), by = 7)){
  if(j == 52){j <- 0}
  j <- j + 1
  k <- k + 1
  pcslist[[k]] <- sum(all.red$pcs[i : (i + 6)])
  weeklist[[k]] <- j
  datelist[[k]] <- all.red$date[i]
}

distr.weekly <- data.frame(week = unlist(weeklist), 
                           startdate = as.Date.numeric(unlist(datelist), origin = "1970-01-01"), 
                           pcs = unlist(pcslist))
```

```{r}
ggplot(data = distr.weekly, aes(x = startdate, y = pcs)) + 
  geom_line() + 
  geom_smooth(data = distr.weekly[1:150,], aes(x = startdate, y = pcs), method = "lm", inherit.aes = FALSE) +
  geom_smooth(data = distr.weekly[151:287,], aes(x = startdate, y = pcs), method = "lm", inherit.aes = FALSE) +
  labs(title = "Weekly Distribution",
       subtitle = "Trend turns around 2017 and variance increases",
       x = "", y = "blood bags") +
  theme_bw()
```

